/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author augus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        btnManipularPecas = new javax.swing.JButton();
        btnAbastecerEstoque = new javax.swing.JButton();
        btnRealizarVenda = new javax.swing.JButton();
        btnCadCliente = new javax.swing.JButton();
        btnCadPeca = new javax.swing.JButton();
        label1 = new java.awt.Label();
        btnSair = new javax.swing.JButton();
        btnReceptaculos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadMenu1 = new javax.swing.JMenu();
        menuAbastecerEstoque = new javax.swing.JMenuItem();
        menuManipularPecas = new javax.swing.JMenuItem();
        menuManipularPecas1 = new javax.swing.JMenuItem();
        menuRealizarVenda = new javax.swing.JMenuItem();
        cadMenu2 = new javax.swing.JMenu();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadPeca = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnManipularPecas.setText("Ordem de Compra");
        btnManipularPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManipularPecasActionPerformed(evt);
            }
        });

        btnAbastecerEstoque.setText("Abastecer Estoque");
        btnAbastecerEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbastecerEstoqueActionPerformed(evt);
            }
        });

        btnRealizarVenda.setText("Realizar Venda");
        btnRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVendaActionPerformed(evt);
            }
        });

        btnCadCliente.setText("Castrar Cliente");
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteActionPerformed(evt);
            }
        });

        btnCadPeca.setText("Cadastrar Peça");
        btnCadPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPecaActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 102, 0));
        label1.setText("Sistema de Almoxarifado");

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnReceptaculos.setText("Receptáculos");
        btnReceptaculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptaculosActionPerformed(evt);
            }
        });

        cadMenu1.setText("Menu");

        menuAbastecerEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuAbastecerEstoque.setText("Abastecer Estoque");
        menuAbastecerEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbastecerEstoqueActionPerformed(evt);
            }
        });
        cadMenu1.add(menuAbastecerEstoque);

        menuManipularPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuManipularPecas.setText("Ordem Compra");
        cadMenu1.add(menuManipularPecas);

        menuManipularPecas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuManipularPecas1.setText("Receptaculos");
        menuManipularPecas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManipularPecas1ActionPerformed(evt);
            }
        });
        cadMenu1.add(menuManipularPecas1);

        menuRealizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuRealizarVenda.setText("Realizar Venda");
        menuRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRealizarVendaActionPerformed(evt);
            }
        });
        cadMenu1.add(menuRealizarVenda);

        jMenuBar1.add(cadMenu1);

        cadMenu2.setText("Realizar Cadastro");

        menuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadCliente.setText("Cadastrar cliente");
        menuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClienteActionPerformed(evt);
            }
        });
        cadMenu2.add(menuCadCliente);

        menuCadPeca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadPeca.setText("Cadastrar peca");
        menuCadPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadPecaActionPerformed(evt);
            }
        });
        cadMenu2.add(menuCadPeca);

        jMenuBar1.add(cadMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadPeca)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRealizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAbastecerEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManipularPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReceptaculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAbastecerEstoque)
                .addGap(18, 18, 18)
                .addComponent(btnManipularPecas)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarVenda)
                .addGap(18, 18, 18)
                .addComponent(btnReceptaculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(16, 16, 16))
        );

        label1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed
        TelaCadastrarCliente t = new TelaCadastrarCliente();
        t.setVisible(true);
    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnCadPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPecaActionPerformed
        TelaCadastrarPeca t = new TelaCadastrarPeca();
        t.setVisible(true);
    }//GEN-LAST:event_btnCadPecaActionPerformed

    private void menuRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRealizarVendaActionPerformed
        TelaRealizarVenda t = new TelaRealizarVenda();
        t.setVisible(true);
    }//GEN-LAST:event_menuRealizarVendaActionPerformed

    private void menuAbastecerEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbastecerEstoqueActionPerformed
        TelaAbastecerEstoque t = new TelaAbastecerEstoque();
        t.setVisible(true);
    }//GEN-LAST:event_menuAbastecerEstoqueActionPerformed

    private void menuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClienteActionPerformed
        TelaCadastrarCliente t = new TelaCadastrarCliente();
        t.setVisible(true);
    }//GEN-LAST:event_menuCadClienteActionPerformed

    private void menuCadPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadPecaActionPerformed
        TelaCadastrarPeca t = new TelaCadastrarPeca();
        t.setVisible(true);
    }//GEN-LAST:event_menuCadPecaActionPerformed

    private void btnAbastecerEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbastecerEstoqueActionPerformed
        TelaAbastecerEstoque t = new TelaAbastecerEstoque();
        t.setVisible(true);
    }//GEN-LAST:event_btnAbastecerEstoqueActionPerformed

    private void btnRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVendaActionPerformed
        TelaRealizarVenda t = new TelaRealizarVenda();
        t.setVisible(true);
    }//GEN-LAST:event_btnRealizarVendaActionPerformed

    private void btnManipularPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManipularPecasActionPerformed
        TelaOrdemCompra t = new TelaOrdemCompra();
        t.setVisible(true);
    }//GEN-LAST:event_btnManipularPecasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnReceptaculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptaculosActionPerformed
        TelaReceptaculos t = new TelaReceptaculos();
        t.setVisible(true);
    }//GEN-LAST:event_btnReceptaculosActionPerformed

    private void menuManipularPecas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManipularPecas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuManipularPecas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbastecerEstoque;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadPeca;
    private javax.swing.JButton btnManipularPecas;
    private javax.swing.JButton btnRealizarVenda;
    private javax.swing.JButton btnReceptaculos;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu cadMenu1;
    private javax.swing.JMenu cadMenu2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.Label label1;
    private javax.swing.JMenuItem menuAbastecerEstoque;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadPeca;
    private javax.swing.JMenuItem menuManipularPecas;
    private javax.swing.JMenuItem menuManipularPecas1;
    private javax.swing.JMenuItem menuRealizarVenda;
    // End of variables declaration//GEN-END:variables
}
